[versions]
junit-jupiter = '6.0.1'
mockito = '5.20.0'
assertj = '3.27.6'
commercetools = '19.6.2'
jackson = '2.20.1'
testcontainers = '1.21.3'
picocli = '4.7.7'
mockserver = '5.15.0'
slf4j = '2.0.17'
logback = '1.5.21'
vanniktech-maven-publish = '0.35.0'
reckon = '1.0.1'
guava = '33.5.0-jre'

[libraries]
commercetools-java-importapi = { module = "com.commercetools.sdk:commercetools-sdk-java-importapi", version.ref = "commercetools" }
commercetools-java-api = { module = "com.commercetools.sdk:commercetools-sdk-java-api", version.ref = "commercetools" }
commercetools-okhttp-client4 = { module = "com.commercetools.sdk:commercetools-okhttp-client4", version.ref = "commercetools" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = 'org.junit.platform:junit-platform-launcher' }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-mockserver = { module = "org.testcontainers:mockserver", version.ref = "testcontainers" }
mockserver-client = { module = "org.mock-server:mockserver-client-java", version.ref = "mockserver" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
reckon = { id = "org.ajoberstar.reckon", version.ref = "reckon" }
