[versions]
junit-jupiter = '6.0.2'
mockito = '5.21.0'
assertj = '3.27.7'
commercetools = '19.7.2'
jackson = '3.0.4'
picocli = '4.7.7'
slf4j = '2.0.17'
logback = '1.5.29'
vanniktech-maven-publish = '0.36.0'
cyclonedx-bom = '3.2.0'
wiremock = '3.13.2'

reckon = '2.0.0'
guava = '33.5.0-jre'

[libraries]
commercetools-java-importapi = { module = "com.commercetools.sdk:commercetools-sdk-java-importapi", version.ref = "commercetools" }
commercetools-java-api = { module = "com.commercetools.sdk:commercetools-sdk-java-api", version.ref = "commercetools" }
commercetools-okhttp-client4 = { module = "com.commercetools.sdk:commercetools-okhttp-client4", version.ref = "commercetools" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = 'org.junit.platform:junit-platform-launcher' }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cyclonedx-bom" }
reckon = { id = "org.ajoberstar.reckon", version.ref = "reckon" }
